### PR TITLE
Rc/docsmodularupdate

### PR DESCRIPTION
**Pull request by Rahat-ch**

### CODE REVIEW

**Comment by Rahat-ch** [comment]
Hey @tomarsachin2271 @livingrockrises @AmanRaj1608 

Would be good to get a check here of the preliminary updates to docs based on the modular updates the code changes involve alot of things copy and pasted and moved around, these are the main changes here: 

Quick start and all tutorials now incllude and ECDSA module set up so everything is Smart Account V2 by default: 
https://docs-neon-eight.vercel.app/docs/quickstart

Added a new tutorial on multichain: 
https://docs-neon-eight.vercel.app/docs/tutorials/nodejs/multichainmint

Info on modules: 
https://docs-neon-eight.vercel.app/docs/Biconomy%20AA%20Stack/Modules/description

Let me know any thoughts so far - I created a section as well for Smart Account V1:
https://docs-neon-eight.vercel.app/docs/category/smart-account-v1

**Comment by tomarsachin2271** [comment]
Screenshot 2023-09-20 at 12 00 19 AM

Whole section brought inside the hint section.

**Comment by tomarsachin2271** [comment]
Biconomy AA Stack => Smart Accounts => Installation 
Biconomy AA Stack => Smart Accounts => Initialization

page is not updated.

**Comment by Rahat-ch** [comment]
> Biconomy AA Stack => Smart Accounts => Installation Biconomy AA Stack => Smart Accounts => Initialization
> 
> page is not updated.

updated in new push

**Review by tomarsachin2271 — APPROVED** [review]

**Pull request merged**
